### ISSUE TITLE
以勒出来当偶像练习生

### ISSUE THREAD

**Issue by TansuoTro** [8MiYile/MCQA#2]
z？
出来打碟

**Comment by 8MiYile** [comment]
WDNMD

**Comment by TansuoTro** [comment]
![以勒给我变成他](https://user-images.githubusercontent.com/40848544/75544040-1bea7f80-5a5e-11ea-94c5-e638417f3519.png)

**Comment by 8MiYile** [comment]
鸡你太美（）
